name: Docker Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build Docker image
        run: docker build -t my-image .

      # Run a temporary container with the mounted volume to list files in the host
      - name: List files in host directory
        run: docker run --rm -v $(pwd):/host alpine ls -la /host

      # Here you should be able to find the path to docker-compose.yml on the host
      # Update the next step accordingly

      - name: Deploy with Docker Compose
        run: docker-compose -f /path/to/docker-compose.yml up -d
