name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.22.1'

      - name: Build and run Simulator
        working-directory: ./simulator
        run: |
          go build -o simulator main.go
          ./simulator &

      - name: Build and run CMD
        working-directory: ./cmd
        run: |
          go build -o cmd main.go
          ./cmd
