name: Docker Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build Docker image
        run: docker build -t my-image .

      - name: Run Docker container
        run: docker run -d --name my-container my-image

      - name: List files in container
        run: docker exec my-container ls -la

      # Here you will see the output of 'ls -la' command in container
      # Find the path to docker-compose.yml and update the next step accordingly

      - name: Deploy with Docker Compose
        run: docker exec my-container docker-compose -f /path/to/docker-compose.yml up -d
