name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.22.2

      - name: Build Simulator
        working-directory: ./simulator
        run: go build -o simulator main.go

      - name: Run Simulator
        working-directory: ./simulator
        run: ./simulator &

      - name: Build CMD
        working-directory: ./cmd
        run: go build -o cmd main.go

      - name: Run CMD
        working-directory: ./cmd
        run: ./cmd

#      - name: Run tests
#        run: go test ./...
