name: Docker Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build Docker image
        run: docker build -t my-image .

      - name: List files in host directory
        run: docker run --rm -v $(pwd):/host alpine ls -la /host

      - name: Display contents of docker-compose.yml
        run: cat /host/docker-compose.yml

      - name: Deploy with Docker Compose
        run: docker-compose -f /host/docker-compose.yml up -d
